// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bthjytuxnpxrcvrdlxpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0aGp5dHV4bnB4cmN2cmRseHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTQwMjAsImV4cCI6MjA1Njk5MDAyMH0.0xvhw7YuOCxbgvCc3QUVWHSrOwwqHk7cs7Myu9p3zVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);